version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ctem-postgres
    environment:
      POSTGRES_DB: ctem_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ctem-network

  redis:
    image: redis:7-alpine
    container_name: ctem-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ctem-network

volumes:
  postgres_data:
  redis_data:

networks:
  ctem-network:
    driver: bridge